# SPDX-License-Identifier: Apache-2.0
"""Generate deterministic OpenAPI and the tiny Sprint 0 TypeScript client."""

import argparse
import json
from pathlib import Path

from oak.interfaces.api.app import app

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "openapi" / "oak.openapi.json"
CLIENT_PATH = ROOT / "web" / "src" / "generated" / "api.ts"

CLIENT_SOURCE = """// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_openapi.py. Do not edit directly.

export interface VersionResponse {
  readonly name: string;
  readonly version: string;
  readonly commit: string;
  readonly schema_versions: readonly string[];
}

export async function getVersion(baseUrl = \"\"): Promise<VersionResponse> {
  const response = await fetch(`${baseUrl}/version`, {
    headers: { Accept: \"application/json\" },
  });
  if (!response.ok) {
    throw new Error(`Version request failed with status ${response.status}`);
  }
  return (await response.json()) as VersionResponse;
}
"""


def _openapi_source() -> str:
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def _check(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    outputs = ((OPENAPI_PATH, _openapi_source()), (CLIENT_PATH, CLIENT_SOURCE))
    if arguments.check:
        stale = [
            str(path.relative_to(ROOT)) for path, source in outputs if not _check(path, source)
        ]
        if stale:
            print("generated files are stale: " + ", ".join(stale))
            return 1
        return 0
    for path, source in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
