# SPDX-License-Identifier: Apache-2.0
"""Generate deterministic OpenAPI and the typed Community web client."""

import argparse
import json
from pathlib import Path

from oak.interfaces.api.app import app

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "openapi" / "oak.openapi.json"
CLIENT_PATH = ROOT / "web" / "src" / "generated" / "api.ts"

CLIENT_SOURCE = """// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate_openapi.py. Do not edit directly.

export type JsonObject = Readonly<Record<string, unknown>>;
export type OperationState =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelling"
  | "cancelled";

export interface VersionResponse {
  readonly name: string;
  readonly version: string;
  readonly commit: string;
  readonly schema_versions: readonly string[];
}

export interface Problem {
  readonly type: string;
  readonly title: string;
  readonly status: number;
  readonly code: string;
  readonly detail: string;
  readonly correlation_id: string | null;
  readonly retriable: boolean;
  readonly errors: readonly Readonly<{ path: string; message: string }>[];
}

export interface DesignCaseResponse {
  readonly case: JsonObject;
  readonly intent: JsonObject | null;
  readonly duplicate: boolean;
}

export interface DesignCaseListResponse {
  readonly items: readonly JsonObject[];
  readonly next_cursor: string | null;
}

export interface AuditTrailResponse {
  readonly items: readonly JsonObject[];
  readonly next_cursor: string | null;
}

export interface OperationResponse {
  readonly operation_id: string;
  readonly workspace_id: string;
  readonly case_id: string;
  readonly kind: string;
  readonly state: OperationState;
  readonly version: number;
  readonly result: JsonObject | null;
  readonly problem: JsonObject | null;
  readonly correlation_id: string;
  readonly attempt_count: number;
  readonly max_attempts: number;
  readonly next_attempt_at: string;
  readonly lease_expires_at: string | null;
  readonly cancel_requested: boolean;
  readonly checkpoint: JsonObject | null;
  readonly created_at: string;
  readonly updated_at: string;
  readonly completed_at: string | null;
  readonly duplicate: boolean;
}

export interface CandidateListResponse {
  readonly items: readonly JsonObject[];
  readonly next_cursor: string | null;
}

export interface ArtifactListResponse {
  readonly items: readonly JsonObject[];
  readonly next_cursor: string | null;
}

export interface OutboxLagResponse {
  readonly pending_events: number;
  readonly oldest_pending_at: string | null;
  readonly latest_sequence: number;
  readonly indexed_through: number;
  readonly sequence_lag: number;
}

export interface SelectionResponse {
  readonly case: JsonObject;
  readonly decision: JsonObject;
  readonly duplicate: boolean;
}

export interface AssuranceResponse {
  readonly case: JsonObject;
  readonly assurance_plan: JsonObject;
  readonly duplicate: boolean;
}

export interface CanonicalExport {
  readonly export_version: "0.1.0";
  readonly manifest: JsonObject;
  readonly objects: readonly Readonly<{
    digest: string;
    content_base64: string;
  }>[];
}

export interface CommandOptions {
  readonly idempotencyKey: string;
  readonly etag?: string;
  readonly correlationId?: string;
  readonly actor?: string;
  readonly tenantId?: string;
  readonly baseUrl?: string;
}

export class OakApiError extends Error {
  constructor(readonly problem: Problem) {
    super(`${problem.code}: ${problem.detail}`);
  }
}

function commandHeaders(options: CommandOptions): HeadersInit {
  const headers: Record<string, string> = {
    Accept: "application/json",
    "Content-Type": "application/json",
    "Idempotency-Key": options.idempotencyKey,
  };
  if (options.etag !== undefined) headers["If-Match"] = options.etag;
  if (options.correlationId !== undefined)
    headers["X-Correlation-ID"] = options.correlationId;
  if (options.actor !== undefined) headers["X-OAK-Actor"] = options.actor;
  if (options.tenantId !== undefined)
    headers["X-OAK-Tenant"] = options.tenantId;
  return headers;
}

async function requestJson<T>(
  path: string,
  init: RequestInit = {},
  baseUrl = "",
): Promise<T> {
  const response = await fetch(`${baseUrl}${path}`, init);
  if (!response.ok) {
    throw new OakApiError((await response.json()) as Problem);
  }
  return (await response.json()) as T;
}

export async function getVersion(baseUrl = ""): Promise<VersionResponse> {
  return requestJson<VersionResponse>(
    "/version",
    { headers: { Accept: "application/json" } },
    baseUrl,
  );
}

export async function createDesignCase(
  input: Readonly<{ original_name: string; content: string }>,
  options: CommandOptions,
): Promise<DesignCaseResponse> {
  return requestJson<DesignCaseResponse>(
    "/v1/design-cases",
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify(input),
    },
    options.baseUrl,
  );
}

export async function getDesignCase(
  caseId: string,
  baseUrl = "",
): Promise<DesignCaseResponse> {
  return requestJson<DesignCaseResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}`,
    {},
    baseUrl,
  );
}

export async function listDesignCases(
  cursor?: string,
  baseUrl = "",
): Promise<DesignCaseListResponse> {
  const query =
    cursor === undefined ? "" : `?cursor=${encodeURIComponent(cursor)}`;
  return requestJson<DesignCaseListResponse>(
    `/v1/design-cases${query}`,
    {},
    baseUrl,
  );
}

export async function listAuditEvents(
  caseId: string,
  cursor?: string,
  baseUrl = "",
): Promise<AuditTrailResponse> {
  const query =
    cursor === undefined ? "" : `?cursor=${encodeURIComponent(cursor)}`;
  return requestJson<AuditTrailResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}/audit${query}`,
    {},
    baseUrl,
  );
}

export async function interpretDesignCase(
  caseId: string,
  options: CommandOptions,
): Promise<DesignCaseResponse> {
  return requestJson<DesignCaseResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}:interpret`,
    { method: "POST", headers: commandHeaders(options) },
    options.baseUrl,
  );
}

export async function confirmDesignCase(
  caseId: string,
  answers: JsonObject,
  options: CommandOptions,
): Promise<DesignCaseResponse> {
  return requestJson<DesignCaseResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}:confirm`,
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify({ answers }),
    },
    options.baseUrl,
  );
}

export async function generateCandidates(
  caseId: string,
  options: CommandOptions,
): Promise<OperationResponse> {
  return requestJson<OperationResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}:generate-candidates`,
    { method: "POST", headers: commandHeaders(options) },
    options.baseUrl,
  );
}

export async function listCandidates(
  caseId: string,
  cursor?: string,
  baseUrl = "",
): Promise<CandidateListResponse> {
  const query =
    cursor === undefined ? "" : `?cursor=${encodeURIComponent(cursor)}`;
  return requestJson<CandidateListResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}/candidates${query}`,
    {},
    baseUrl,
  );
}

export async function evaluateCandidate(
  caseId: string,
  candidateId: string,
  options: CommandOptions,
): Promise<OperationResponse> {
  return requestJson<OperationResponse>(
    `/v1/candidates/${encodeURIComponent(candidateId)}:evaluate`,
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify({ case_id: caseId }),
    },
    options.baseUrl,
  );
}

export async function selectCandidate(
  caseId: string,
  input: Readonly<{ candidate_id: string; rationale: string }>,
  options: CommandOptions,
): Promise<SelectionResponse> {
  return requestJson<SelectionResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}:select-candidate`,
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify(input),
    },
    options.baseUrl,
  );
}

export async function createAssurancePlan(
  caseId: string,
  candidateId: string,
  options: CommandOptions,
): Promise<AssuranceResponse> {
  return requestJson<AssuranceResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}:create-assurance-plan`,
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify({ candidate_id: candidateId }),
    },
    options.baseUrl,
  );
}

export async function compileBundle(
  caseId: string,
  input: Readonly<{ candidate_id: string; target: JsonObject }>,
  options: CommandOptions,
): Promise<OperationResponse> {
  return requestJson<OperationResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}:compile`,
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify(input),
    },
    options.baseUrl,
  );
}

export interface ArtifactReference {
  readonly id: string;
  readonly version: string;
  readonly digest: string;
}

export async function listArtifacts(
  caseId: string,
  cursor?: string,
  baseUrl = "",
): Promise<ArtifactListResponse> {
  const query =
    cursor === undefined ? "" : `?cursor=${encodeURIComponent(cursor)}`;
  return requestJson<ArtifactListResponse>(
    `/v1/design-cases/${encodeURIComponent(caseId)}/artifacts${query}`,
    {},
    baseUrl,
  );
}

export async function getJsonArtifact(
  caseId: string,
  reference: ArtifactReference,
  baseUrl = "",
): Promise<JsonObject> {
  const version = encodeURIComponent(reference.version);
  const digest = encodeURIComponent(reference.digest);
  const query = `?version=${version}&digest=${digest}`;
  return requestJson<JsonObject>(
    `/v1/design-cases/${encodeURIComponent(caseId)}/artifacts/${encodeURIComponent(reference.id)}${query}`,
    {},
    baseUrl,
  );
}

export async function getOperation(
  operationId: string,
  baseUrl = "",
): Promise<OperationResponse> {
  return requestJson<OperationResponse>(
    `/v1/operations/${encodeURIComponent(operationId)}`,
    {},
    baseUrl,
  );
}

export async function getOutboxLag(baseUrl = ""): Promise<OutboxLagResponse> {
  return requestJson<OutboxLagResponse>("/v1/system/outbox-lag", {}, baseUrl);
}

export async function cancelOperation(
  operationId: string,
  options: CommandOptions,
): Promise<OperationResponse> {
  return requestJson<OperationResponse>(
    `/v1/operations/${encodeURIComponent(operationId)}:cancel`,
    { method: "POST", headers: commandHeaders(options) },
    options.baseUrl,
  );
}

export async function exportDesignCase(
  caseId: string,
  baseUrl = "",
): Promise<CanonicalExport> {
  return requestJson<CanonicalExport>(
    `/v1/design-cases/${encodeURIComponent(caseId)}/export`,
    {},
    baseUrl,
  );
}

export async function importDesignCase(
  exported: CanonicalExport,
  options: CommandOptions,
): Promise<DesignCaseResponse> {
  return requestJson<DesignCaseResponse>(
    "/v1/design-cases:import",
    {
      method: "POST",
      headers: commandHeaders(options),
      body: JSON.stringify(exported),
    },
    options.baseUrl,
  );
}
"""


def _openapi_source() -> str:
    return json.dumps(app.openapi(), indent=2, sort_keys=True) + "\n"


def _check(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    outputs = ((OPENAPI_PATH, _openapi_source()), (CLIENT_PATH, CLIENT_SOURCE))
    if arguments.check:
        stale = [
            str(path.relative_to(ROOT)) for path, source in outputs if not _check(path, source)
        ]
        if stale:
            print("generated files are stale: " + ", ".join(stale))
            return 1
        return 0
    for path, source in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
